CREATE DATABASE QuanLyKhachSan;
GO

USE QuanLyKhachSan;
GO



CREATE TABLE PHONG (
	MaPhong VARCHAR(10) PRIMARY KEY,
	LoaiPhong NVARCHAR(30),
	GiaPhong DECIMAL(7, 2),
	TinhTrang NVARCHAR(30)
)
GO

CREATE TABLE KHACHHANG (
	MaKhachHang VARCHAR(10) PRIMARY KEY,
	TenKhachHang NVARCHAR(30),
	CMND VARCHAR(15),
	SoDienThoai VARCHAR(15)
)
GO

CREATE TABLE HOADON (
	MaHoaDon VARCHAR(10) PRIMARY KEY,
	NgayNhanPhong DATE,
	NgayTraPhong DATE,
	TongTien DECIMAL(7, 2),
	MaKhachHang VARCHAR(10) FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang),
	MaPhong VARCHAR(10) FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong)
)
GO

ALTER TABLE HOADON
ALTER COLUMN TongTien DECIMAL(15, 2);
ALTER TABLE PHONG
ALTER COLUMN GiaPhong DECIMAL(15, 2);